# Generated by Django 5.1.3 on 2024-11-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemaambiental',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
