# Generated by Django 5.1.3 on 2024-11-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicio', '0002_alter_problemaambiental_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problemasambientales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
