# Generated by Django 5.1.3 on 2024-11-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicio', '0003_problemasambientales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('puntaje', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProblemaAmbiental',
        ),
        migrations.DeleteModel(
            name='Problemasambientales',
        ),
    ]
