# Generated by Django 5.1.3 on 2024-11-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicio', '0004_resultadojuego_delete_problemaambiental_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puntaje', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ResultadoJuego',
        ),
    ]
