# Generated by Django 5.1.3 on 2024-11-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicio', '0005_puntaje_delete_resultadojuego'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntaje',
            name='fecha',
        ),
    ]
